//this code generated by T4

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Controls.Primitives;
using System.ComponentModel;
using System.Windows.Interop;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Documents.Serialization;
using System.Windows.Input;
using System.Windows.Media.Animation;
using System.Windows.Media;
using System.Windows.Media.TextFormatting;
using System.Windows.Annotations;
using System.Windows.Ink;
using System.Windows.Automation.Peers;
using System.Windows.Markup.Localizer;
using System.Windows.Media.Imaging;
using System.IO.Packaging;
using System.Security.RightsManagement;
using System.Windows.Threading;
using System.Windows.Media.Effects;
using System.Windows.Shell;
using System.Security.Permissions;
using System.Windows.Annotations.Storage;
using System.Diagnostics;

namespace Livet.Converters
{
    public class BaseValueSourceAndBooleanConverter : IValueConverter
    {
        //VM→View
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is bool)) throw new ArgumentException();

            if ((bool)value)
            {
                if (_isConvertWhenTrueSet)
                {
                    return ConvertWhenTrue;
                }
            }
            else
            {
                if (_isConvertWhenFalseSet)
                {
                    return ConvertWhenFalse;
                }
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertWhenTrueSet;
        private BaseValueSource _convertWhenTrue;
        public BaseValueSource ConvertWhenTrue
        {
            get
            {
                return _convertWhenTrue;
            }
            set
            {
                _convertWhenTrue = value;
                _isConvertWhenTrueSet = true;
            }
        }

        private bool _isConvertWhenFalseSet;
        private BaseValueSource _convertWhenFalse;
        public BaseValueSource ConvertWhenFalse
        {
            get
            {
                return _convertWhenFalse;
            }
            set
            {
                _convertWhenFalse = value;
                _isConvertWhenFalseSet = true;
            }
        }

        //View→VM
        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is BaseValueSource)) throw new ArgumentException();

            var enumValue = (BaseValueSource)value;

			switch(enumValue.ToString())
			{
				case "Unknown":
					if (_isConvertBackWhenUnknownSet)
					{
						return ConvertBackWhenUnknown;
					}
					break;
				case "Default":
					if (_isConvertBackWhenDefaultSet)
					{
						return ConvertBackWhenDefault;
					}
					break;
				case "Inherited":
					if (_isConvertBackWhenInheritedSet)
					{
						return ConvertBackWhenInherited;
					}
					break;
				case "DefaultStyle":
					if (_isConvertBackWhenDefaultStyleSet)
					{
						return ConvertBackWhenDefaultStyle;
					}
					break;
				case "DefaultStyleTrigger":
					if (_isConvertBackWhenDefaultStyleTriggerSet)
					{
						return ConvertBackWhenDefaultStyleTrigger;
					}
					break;
				case "Style":
					if (_isConvertBackWhenStyleSet)
					{
						return ConvertBackWhenStyle;
					}
					break;
				case "TemplateTrigger":
					if (_isConvertBackWhenTemplateTriggerSet)
					{
						return ConvertBackWhenTemplateTrigger;
					}
					break;
				case "StyleTrigger":
					if (_isConvertBackWhenStyleTriggerSet)
					{
						return ConvertBackWhenStyleTrigger;
					}
					break;
				case "ImplicitStyleReference":
					if (_isConvertBackWhenImplicitStyleReferenceSet)
					{
						return ConvertBackWhenImplicitStyleReference;
					}
					break;
				case "ParentTemplate":
					if (_isConvertBackWhenParentTemplateSet)
					{
						return ConvertBackWhenParentTemplate;
					}
					break;
				case "ParentTemplateTrigger":
					if (_isConvertBackWhenParentTemplateTriggerSet)
					{
						return ConvertBackWhenParentTemplateTrigger;
					}
					break;
				case "Local":
					if (_isConvertBackWhenLocalSet)
					{
						return ConvertBackWhenLocal;
					}
					break;
				default:
					throw new ArgumentException();
			}

            if (_isConvertBackDefaultBooleanValueSet)
            {
                return ConvertBackDefaultBooleanValue;
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertBackDefaultBooleanValueSet;
        private bool _convertBackDefaultBooleanValue;
        public bool ConvertBackDefaultBooleanValue
        {
            get
            {
                return _convertBackDefaultBooleanValue;
            }
            set
            {
                _convertBackDefaultBooleanValue = value;
				_isConvertBackDefaultBooleanValueSet = true;
            }
        }

        private bool _isConvertBackWhenUnknownSet;
        private bool _convertBackWhenUnknown;

        public bool ConvertBackWhenUnknown
        {
            get
            {
                return _convertBackWhenUnknown;
            }
            set
            {
                _convertBackWhenUnknown = value;
                _isConvertBackWhenUnknownSet = true;
            }
        }
        private bool _isConvertBackWhenDefaultSet;
        private bool _convertBackWhenDefault;

        public bool ConvertBackWhenDefault
        {
            get
            {
                return _convertBackWhenDefault;
            }
            set
            {
                _convertBackWhenDefault = value;
                _isConvertBackWhenDefaultSet = true;
            }
        }
        private bool _isConvertBackWhenInheritedSet;
        private bool _convertBackWhenInherited;

        public bool ConvertBackWhenInherited
        {
            get
            {
                return _convertBackWhenInherited;
            }
            set
            {
                _convertBackWhenInherited = value;
                _isConvertBackWhenInheritedSet = true;
            }
        }
        private bool _isConvertBackWhenDefaultStyleSet;
        private bool _convertBackWhenDefaultStyle;

        public bool ConvertBackWhenDefaultStyle
        {
            get
            {
                return _convertBackWhenDefaultStyle;
            }
            set
            {
                _convertBackWhenDefaultStyle = value;
                _isConvertBackWhenDefaultStyleSet = true;
            }
        }
        private bool _isConvertBackWhenDefaultStyleTriggerSet;
        private bool _convertBackWhenDefaultStyleTrigger;

        public bool ConvertBackWhenDefaultStyleTrigger
        {
            get
            {
                return _convertBackWhenDefaultStyleTrigger;
            }
            set
            {
                _convertBackWhenDefaultStyleTrigger = value;
                _isConvertBackWhenDefaultStyleTriggerSet = true;
            }
        }
        private bool _isConvertBackWhenStyleSet;
        private bool _convertBackWhenStyle;

        public bool ConvertBackWhenStyle
        {
            get
            {
                return _convertBackWhenStyle;
            }
            set
            {
                _convertBackWhenStyle = value;
                _isConvertBackWhenStyleSet = true;
            }
        }
        private bool _isConvertBackWhenTemplateTriggerSet;
        private bool _convertBackWhenTemplateTrigger;

        public bool ConvertBackWhenTemplateTrigger
        {
            get
            {
                return _convertBackWhenTemplateTrigger;
            }
            set
            {
                _convertBackWhenTemplateTrigger = value;
                _isConvertBackWhenTemplateTriggerSet = true;
            }
        }
        private bool _isConvertBackWhenStyleTriggerSet;
        private bool _convertBackWhenStyleTrigger;

        public bool ConvertBackWhenStyleTrigger
        {
            get
            {
                return _convertBackWhenStyleTrigger;
            }
            set
            {
                _convertBackWhenStyleTrigger = value;
                _isConvertBackWhenStyleTriggerSet = true;
            }
        }
        private bool _isConvertBackWhenImplicitStyleReferenceSet;
        private bool _convertBackWhenImplicitStyleReference;

        public bool ConvertBackWhenImplicitStyleReference
        {
            get
            {
                return _convertBackWhenImplicitStyleReference;
            }
            set
            {
                _convertBackWhenImplicitStyleReference = value;
                _isConvertBackWhenImplicitStyleReferenceSet = true;
            }
        }
        private bool _isConvertBackWhenParentTemplateSet;
        private bool _convertBackWhenParentTemplate;

        public bool ConvertBackWhenParentTemplate
        {
            get
            {
                return _convertBackWhenParentTemplate;
            }
            set
            {
                _convertBackWhenParentTemplate = value;
                _isConvertBackWhenParentTemplateSet = true;
            }
        }
        private bool _isConvertBackWhenParentTemplateTriggerSet;
        private bool _convertBackWhenParentTemplateTrigger;

        public bool ConvertBackWhenParentTemplateTrigger
        {
            get
            {
                return _convertBackWhenParentTemplateTrigger;
            }
            set
            {
                _convertBackWhenParentTemplateTrigger = value;
                _isConvertBackWhenParentTemplateTriggerSet = true;
            }
        }
        private bool _isConvertBackWhenLocalSet;
        private bool _convertBackWhenLocal;

        public bool ConvertBackWhenLocal
        {
            get
            {
                return _convertBackWhenLocal;
            }
            set
            {
                _convertBackWhenLocal = value;
                _isConvertBackWhenLocalSet = true;
            }
        }
    }
}