//this code generated by T4

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Controls.Primitives;
using System.ComponentModel;
using System.Windows.Interop;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Documents.Serialization;
using System.Windows.Input;
using System.Windows.Media.Animation;
using System.Windows.Media;
using System.Windows.Media.TextFormatting;
using System.Windows.Annotations;
using System.Windows.Ink;
using System.Windows.Automation.Peers;
using System.Windows.Markup.Localizer;
using System.Windows.Media.Imaging;
using System.IO.Packaging;
using System.Security.RightsManagement;
using System.Windows.Threading;
using System.Windows.Media.Effects;
using System.Windows.Shell;
using System.Security.Permissions;
using System.Windows.Annotations.Storage;
using System.Diagnostics;

namespace Livet.Converters
{
    public class DragDropKeyStatesAndBooleanConverter : IValueConverter
    {
        //VM→View
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is bool)) throw new ArgumentException();

            if ((bool)value)
            {
                if (_isConvertWhenTrueSet)
                {
                    return ConvertWhenTrue;
                }
            }
            else
            {
                if (_isConvertWhenFalseSet)
                {
                    return ConvertWhenFalse;
                }
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertWhenTrueSet;
        private DragDropKeyStates _convertWhenTrue;
        public DragDropKeyStates ConvertWhenTrue
        {
            get
            {
                return _convertWhenTrue;
            }
            set
            {
                _convertWhenTrue = value;
                _isConvertWhenTrueSet = true;
            }
        }

        private bool _isConvertWhenFalseSet;
        private DragDropKeyStates _convertWhenFalse;
        public DragDropKeyStates ConvertWhenFalse
        {
            get
            {
                return _convertWhenFalse;
            }
            set
            {
                _convertWhenFalse = value;
                _isConvertWhenFalseSet = true;
            }
        }

        //View→VM
        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is DragDropKeyStates)) throw new ArgumentException();

            var enumValue = (DragDropKeyStates)value;

			switch(enumValue.ToString())
			{
				case "None":
					if (_isConvertBackWhenNoneSet)
					{
						return ConvertBackWhenNone;
					}
					break;
				case "LeftMouseButton":
					if (_isConvertBackWhenLeftMouseButtonSet)
					{
						return ConvertBackWhenLeftMouseButton;
					}
					break;
				case "RightMouseButton":
					if (_isConvertBackWhenRightMouseButtonSet)
					{
						return ConvertBackWhenRightMouseButton;
					}
					break;
				case "ShiftKey":
					if (_isConvertBackWhenShiftKeySet)
					{
						return ConvertBackWhenShiftKey;
					}
					break;
				case "ControlKey":
					if (_isConvertBackWhenControlKeySet)
					{
						return ConvertBackWhenControlKey;
					}
					break;
				case "MiddleMouseButton":
					if (_isConvertBackWhenMiddleMouseButtonSet)
					{
						return ConvertBackWhenMiddleMouseButton;
					}
					break;
				case "AltKey":
					if (_isConvertBackWhenAltKeySet)
					{
						return ConvertBackWhenAltKey;
					}
					break;
				default:
					throw new ArgumentException();
			}

            if (_isConvertBackDefaultBooleanValueSet)
            {
                return ConvertBackDefaultBooleanValue;
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertBackDefaultBooleanValueSet;
        private bool _convertBackDefaultBooleanValue;
        public bool ConvertBackDefaultBooleanValue
        {
            get
            {
                return _convertBackDefaultBooleanValue;
            }
            set
            {
                _convertBackDefaultBooleanValue = value;
				_isConvertBackDefaultBooleanValueSet = true;
            }
        }

        private bool _isConvertBackWhenNoneSet;
        private bool _convertBackWhenNone;

        public bool ConvertBackWhenNone
        {
            get
            {
                return _convertBackWhenNone;
            }
            set
            {
                _convertBackWhenNone = value;
                _isConvertBackWhenNoneSet = true;
            }
        }
        private bool _isConvertBackWhenLeftMouseButtonSet;
        private bool _convertBackWhenLeftMouseButton;

        public bool ConvertBackWhenLeftMouseButton
        {
            get
            {
                return _convertBackWhenLeftMouseButton;
            }
            set
            {
                _convertBackWhenLeftMouseButton = value;
                _isConvertBackWhenLeftMouseButtonSet = true;
            }
        }
        private bool _isConvertBackWhenRightMouseButtonSet;
        private bool _convertBackWhenRightMouseButton;

        public bool ConvertBackWhenRightMouseButton
        {
            get
            {
                return _convertBackWhenRightMouseButton;
            }
            set
            {
                _convertBackWhenRightMouseButton = value;
                _isConvertBackWhenRightMouseButtonSet = true;
            }
        }
        private bool _isConvertBackWhenShiftKeySet;
        private bool _convertBackWhenShiftKey;

        public bool ConvertBackWhenShiftKey
        {
            get
            {
                return _convertBackWhenShiftKey;
            }
            set
            {
                _convertBackWhenShiftKey = value;
                _isConvertBackWhenShiftKeySet = true;
            }
        }
        private bool _isConvertBackWhenControlKeySet;
        private bool _convertBackWhenControlKey;

        public bool ConvertBackWhenControlKey
        {
            get
            {
                return _convertBackWhenControlKey;
            }
            set
            {
                _convertBackWhenControlKey = value;
                _isConvertBackWhenControlKeySet = true;
            }
        }
        private bool _isConvertBackWhenMiddleMouseButtonSet;
        private bool _convertBackWhenMiddleMouseButton;

        public bool ConvertBackWhenMiddleMouseButton
        {
            get
            {
                return _convertBackWhenMiddleMouseButton;
            }
            set
            {
                _convertBackWhenMiddleMouseButton = value;
                _isConvertBackWhenMiddleMouseButtonSet = true;
            }
        }
        private bool _isConvertBackWhenAltKeySet;
        private bool _convertBackWhenAltKey;

        public bool ConvertBackWhenAltKey
        {
            get
            {
                return _convertBackWhenAltKey;
            }
            set
            {
                _convertBackWhenAltKey = value;
                _isConvertBackWhenAltKeySet = true;
            }
        }
    }
}