//this code generated by T4

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Controls.Primitives;
using System.ComponentModel;
using System.Windows.Interop;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Documents.Serialization;
using System.Windows.Input;
using System.Windows.Media.Animation;
using System.Windows.Media;
using System.Windows.Media.TextFormatting;
using System.Windows.Annotations;
using System.Windows.Ink;
using System.Windows.Automation.Peers;
using System.Windows.Markup.Localizer;
using System.Windows.Media.Imaging;
using System.IO.Packaging;
using System.Security.RightsManagement;
using System.Windows.Threading;
using System.Windows.Media.Effects;
using System.Windows.Shell;
using System.Security.Permissions;
using System.Windows.Annotations.Storage;
using System.Diagnostics;

namespace Livet.Converters
{
    public class FigureHorizontalAnchorAndBooleanConverter : IValueConverter
    {
        //VM→View
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is bool)) throw new ArgumentException();

            if ((bool)value)
            {
                if (_isConvertWhenTrueSet)
                {
                    return ConvertWhenTrue;
                }
            }
            else
            {
                if (_isConvertWhenFalseSet)
                {
                    return ConvertWhenFalse;
                }
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertWhenTrueSet;
        private FigureHorizontalAnchor _convertWhenTrue;
        public FigureHorizontalAnchor ConvertWhenTrue
        {
            get
            {
                return _convertWhenTrue;
            }
            set
            {
                _convertWhenTrue = value;
                _isConvertWhenTrueSet = true;
            }
        }

        private bool _isConvertWhenFalseSet;
        private FigureHorizontalAnchor _convertWhenFalse;
        public FigureHorizontalAnchor ConvertWhenFalse
        {
            get
            {
                return _convertWhenFalse;
            }
            set
            {
                _convertWhenFalse = value;
                _isConvertWhenFalseSet = true;
            }
        }

        //View→VM
        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is FigureHorizontalAnchor)) throw new ArgumentException();

            var enumValue = (FigureHorizontalAnchor)value;

			switch(enumValue.ToString())
			{
				case "PageLeft":
					if (_isConvertBackWhenPageLeftSet)
					{
						return ConvertBackWhenPageLeft;
					}
					break;
				case "PageCenter":
					if (_isConvertBackWhenPageCenterSet)
					{
						return ConvertBackWhenPageCenter;
					}
					break;
				case "PageRight":
					if (_isConvertBackWhenPageRightSet)
					{
						return ConvertBackWhenPageRight;
					}
					break;
				case "ContentLeft":
					if (_isConvertBackWhenContentLeftSet)
					{
						return ConvertBackWhenContentLeft;
					}
					break;
				case "ContentCenter":
					if (_isConvertBackWhenContentCenterSet)
					{
						return ConvertBackWhenContentCenter;
					}
					break;
				case "ContentRight":
					if (_isConvertBackWhenContentRightSet)
					{
						return ConvertBackWhenContentRight;
					}
					break;
				case "ColumnLeft":
					if (_isConvertBackWhenColumnLeftSet)
					{
						return ConvertBackWhenColumnLeft;
					}
					break;
				case "ColumnCenter":
					if (_isConvertBackWhenColumnCenterSet)
					{
						return ConvertBackWhenColumnCenter;
					}
					break;
				case "ColumnRight":
					if (_isConvertBackWhenColumnRightSet)
					{
						return ConvertBackWhenColumnRight;
					}
					break;
				default:
					throw new ArgumentException();
			}

            if (_isConvertBackDefaultBooleanValueSet)
            {
                return ConvertBackDefaultBooleanValue;
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertBackDefaultBooleanValueSet;
        private bool _convertBackDefaultBooleanValue;
        public bool ConvertBackDefaultBooleanValue
        {
            get
            {
                return _convertBackDefaultBooleanValue;
            }
            set
            {
                _convertBackDefaultBooleanValue = value;
				_isConvertBackDefaultBooleanValueSet = true;
            }
        }

        private bool _isConvertBackWhenPageLeftSet;
        private bool _convertBackWhenPageLeft;

        public bool ConvertBackWhenPageLeft
        {
            get
            {
                return _convertBackWhenPageLeft;
            }
            set
            {
                _convertBackWhenPageLeft = value;
                _isConvertBackWhenPageLeftSet = true;
            }
        }
        private bool _isConvertBackWhenPageCenterSet;
        private bool _convertBackWhenPageCenter;

        public bool ConvertBackWhenPageCenter
        {
            get
            {
                return _convertBackWhenPageCenter;
            }
            set
            {
                _convertBackWhenPageCenter = value;
                _isConvertBackWhenPageCenterSet = true;
            }
        }
        private bool _isConvertBackWhenPageRightSet;
        private bool _convertBackWhenPageRight;

        public bool ConvertBackWhenPageRight
        {
            get
            {
                return _convertBackWhenPageRight;
            }
            set
            {
                _convertBackWhenPageRight = value;
                _isConvertBackWhenPageRightSet = true;
            }
        }
        private bool _isConvertBackWhenContentLeftSet;
        private bool _convertBackWhenContentLeft;

        public bool ConvertBackWhenContentLeft
        {
            get
            {
                return _convertBackWhenContentLeft;
            }
            set
            {
                _convertBackWhenContentLeft = value;
                _isConvertBackWhenContentLeftSet = true;
            }
        }
        private bool _isConvertBackWhenContentCenterSet;
        private bool _convertBackWhenContentCenter;

        public bool ConvertBackWhenContentCenter
        {
            get
            {
                return _convertBackWhenContentCenter;
            }
            set
            {
                _convertBackWhenContentCenter = value;
                _isConvertBackWhenContentCenterSet = true;
            }
        }
        private bool _isConvertBackWhenContentRightSet;
        private bool _convertBackWhenContentRight;

        public bool ConvertBackWhenContentRight
        {
            get
            {
                return _convertBackWhenContentRight;
            }
            set
            {
                _convertBackWhenContentRight = value;
                _isConvertBackWhenContentRightSet = true;
            }
        }
        private bool _isConvertBackWhenColumnLeftSet;
        private bool _convertBackWhenColumnLeft;

        public bool ConvertBackWhenColumnLeft
        {
            get
            {
                return _convertBackWhenColumnLeft;
            }
            set
            {
                _convertBackWhenColumnLeft = value;
                _isConvertBackWhenColumnLeftSet = true;
            }
        }
        private bool _isConvertBackWhenColumnCenterSet;
        private bool _convertBackWhenColumnCenter;

        public bool ConvertBackWhenColumnCenter
        {
            get
            {
                return _convertBackWhenColumnCenter;
            }
            set
            {
                _convertBackWhenColumnCenter = value;
                _isConvertBackWhenColumnCenterSet = true;
            }
        }
        private bool _isConvertBackWhenColumnRightSet;
        private bool _convertBackWhenColumnRight;

        public bool ConvertBackWhenColumnRight
        {
            get
            {
                return _convertBackWhenColumnRight;
            }
            set
            {
                _convertBackWhenColumnRight = value;
                _isConvertBackWhenColumnRightSet = true;
            }
        }
    }
}