//this code generated by T4

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Controls.Primitives;
using System.ComponentModel;
using System.Windows.Interop;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Documents.Serialization;
using System.Windows.Input;
using System.Windows.Media.Animation;
using System.Windows.Media;
using System.Windows.Media.TextFormatting;
using System.Windows.Annotations;
using System.Windows.Ink;
using System.Windows.Automation.Peers;
using System.Windows.Markup.Localizer;
using System.Windows.Media.Imaging;
using System.IO.Packaging;
using System.Security.RightsManagement;
using System.Windows.Threading;
using System.Windows.Media.Effects;
using System.Windows.Shell;
using System.Security.Permissions;
using System.Windows.Annotations.Storage;
using System.Diagnostics;

namespace Livet.Converters
{
    public class FontEmbeddingRightAndBooleanConverter : IValueConverter
    {
        //VM→View
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is bool)) throw new ArgumentException();

            if ((bool)value)
            {
                if (_isConvertWhenTrueSet)
                {
                    return ConvertWhenTrue;
                }
            }
            else
            {
                if (_isConvertWhenFalseSet)
                {
                    return ConvertWhenFalse;
                }
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertWhenTrueSet;
        private FontEmbeddingRight _convertWhenTrue;
        public FontEmbeddingRight ConvertWhenTrue
        {
            get
            {
                return _convertWhenTrue;
            }
            set
            {
                _convertWhenTrue = value;
                _isConvertWhenTrueSet = true;
            }
        }

        private bool _isConvertWhenFalseSet;
        private FontEmbeddingRight _convertWhenFalse;
        public FontEmbeddingRight ConvertWhenFalse
        {
            get
            {
                return _convertWhenFalse;
            }
            set
            {
                _convertWhenFalse = value;
                _isConvertWhenFalseSet = true;
            }
        }

        //View→VM
        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is FontEmbeddingRight)) throw new ArgumentException();

            var enumValue = (FontEmbeddingRight)value;

			switch(enumValue.ToString())
			{
				case "Installable":
					if (_isConvertBackWhenInstallableSet)
					{
						return ConvertBackWhenInstallable;
					}
					break;
				case "InstallableButNoSubsetting":
					if (_isConvertBackWhenInstallableButNoSubsettingSet)
					{
						return ConvertBackWhenInstallableButNoSubsetting;
					}
					break;
				case "InstallableButWithBitmapsOnly":
					if (_isConvertBackWhenInstallableButWithBitmapsOnlySet)
					{
						return ConvertBackWhenInstallableButWithBitmapsOnly;
					}
					break;
				case "InstallableButNoSubsettingAndWithBitmapsOnly":
					if (_isConvertBackWhenInstallableButNoSubsettingAndWithBitmapsOnlySet)
					{
						return ConvertBackWhenInstallableButNoSubsettingAndWithBitmapsOnly;
					}
					break;
				case "RestrictedLicense":
					if (_isConvertBackWhenRestrictedLicenseSet)
					{
						return ConvertBackWhenRestrictedLicense;
					}
					break;
				case "PreviewAndPrint":
					if (_isConvertBackWhenPreviewAndPrintSet)
					{
						return ConvertBackWhenPreviewAndPrint;
					}
					break;
				case "PreviewAndPrintButNoSubsetting":
					if (_isConvertBackWhenPreviewAndPrintButNoSubsettingSet)
					{
						return ConvertBackWhenPreviewAndPrintButNoSubsetting;
					}
					break;
				case "PreviewAndPrintButWithBitmapsOnly":
					if (_isConvertBackWhenPreviewAndPrintButWithBitmapsOnlySet)
					{
						return ConvertBackWhenPreviewAndPrintButWithBitmapsOnly;
					}
					break;
				case "PreviewAndPrintButNoSubsettingAndWithBitmapsOnly":
					if (_isConvertBackWhenPreviewAndPrintButNoSubsettingAndWithBitmapsOnlySet)
					{
						return ConvertBackWhenPreviewAndPrintButNoSubsettingAndWithBitmapsOnly;
					}
					break;
				case "Editable":
					if (_isConvertBackWhenEditableSet)
					{
						return ConvertBackWhenEditable;
					}
					break;
				case "EditableButNoSubsetting":
					if (_isConvertBackWhenEditableButNoSubsettingSet)
					{
						return ConvertBackWhenEditableButNoSubsetting;
					}
					break;
				case "EditableButWithBitmapsOnly":
					if (_isConvertBackWhenEditableButWithBitmapsOnlySet)
					{
						return ConvertBackWhenEditableButWithBitmapsOnly;
					}
					break;
				case "EditableButNoSubsettingAndWithBitmapsOnly":
					if (_isConvertBackWhenEditableButNoSubsettingAndWithBitmapsOnlySet)
					{
						return ConvertBackWhenEditableButNoSubsettingAndWithBitmapsOnly;
					}
					break;
				default:
					throw new ArgumentException();
			}

            if (_isConvertBackDefaultBooleanValueSet)
            {
                return ConvertBackDefaultBooleanValue;
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertBackDefaultBooleanValueSet;
        private bool _convertBackDefaultBooleanValue;
        public bool ConvertBackDefaultBooleanValue
        {
            get
            {
                return _convertBackDefaultBooleanValue;
            }
            set
            {
                _convertBackDefaultBooleanValue = value;
				_isConvertBackDefaultBooleanValueSet = true;
            }
        }

        private bool _isConvertBackWhenInstallableSet;
        private bool _convertBackWhenInstallable;

        public bool ConvertBackWhenInstallable
        {
            get
            {
                return _convertBackWhenInstallable;
            }
            set
            {
                _convertBackWhenInstallable = value;
                _isConvertBackWhenInstallableSet = true;
            }
        }
        private bool _isConvertBackWhenInstallableButNoSubsettingSet;
        private bool _convertBackWhenInstallableButNoSubsetting;

        public bool ConvertBackWhenInstallableButNoSubsetting
        {
            get
            {
                return _convertBackWhenInstallableButNoSubsetting;
            }
            set
            {
                _convertBackWhenInstallableButNoSubsetting = value;
                _isConvertBackWhenInstallableButNoSubsettingSet = true;
            }
        }
        private bool _isConvertBackWhenInstallableButWithBitmapsOnlySet;
        private bool _convertBackWhenInstallableButWithBitmapsOnly;

        public bool ConvertBackWhenInstallableButWithBitmapsOnly
        {
            get
            {
                return _convertBackWhenInstallableButWithBitmapsOnly;
            }
            set
            {
                _convertBackWhenInstallableButWithBitmapsOnly = value;
                _isConvertBackWhenInstallableButWithBitmapsOnlySet = true;
            }
        }
        private bool _isConvertBackWhenInstallableButNoSubsettingAndWithBitmapsOnlySet;
        private bool _convertBackWhenInstallableButNoSubsettingAndWithBitmapsOnly;

        public bool ConvertBackWhenInstallableButNoSubsettingAndWithBitmapsOnly
        {
            get
            {
                return _convertBackWhenInstallableButNoSubsettingAndWithBitmapsOnly;
            }
            set
            {
                _convertBackWhenInstallableButNoSubsettingAndWithBitmapsOnly = value;
                _isConvertBackWhenInstallableButNoSubsettingAndWithBitmapsOnlySet = true;
            }
        }
        private bool _isConvertBackWhenRestrictedLicenseSet;
        private bool _convertBackWhenRestrictedLicense;

        public bool ConvertBackWhenRestrictedLicense
        {
            get
            {
                return _convertBackWhenRestrictedLicense;
            }
            set
            {
                _convertBackWhenRestrictedLicense = value;
                _isConvertBackWhenRestrictedLicenseSet = true;
            }
        }
        private bool _isConvertBackWhenPreviewAndPrintSet;
        private bool _convertBackWhenPreviewAndPrint;

        public bool ConvertBackWhenPreviewAndPrint
        {
            get
            {
                return _convertBackWhenPreviewAndPrint;
            }
            set
            {
                _convertBackWhenPreviewAndPrint = value;
                _isConvertBackWhenPreviewAndPrintSet = true;
            }
        }
        private bool _isConvertBackWhenPreviewAndPrintButNoSubsettingSet;
        private bool _convertBackWhenPreviewAndPrintButNoSubsetting;

        public bool ConvertBackWhenPreviewAndPrintButNoSubsetting
        {
            get
            {
                return _convertBackWhenPreviewAndPrintButNoSubsetting;
            }
            set
            {
                _convertBackWhenPreviewAndPrintButNoSubsetting = value;
                _isConvertBackWhenPreviewAndPrintButNoSubsettingSet = true;
            }
        }
        private bool _isConvertBackWhenPreviewAndPrintButWithBitmapsOnlySet;
        private bool _convertBackWhenPreviewAndPrintButWithBitmapsOnly;

        public bool ConvertBackWhenPreviewAndPrintButWithBitmapsOnly
        {
            get
            {
                return _convertBackWhenPreviewAndPrintButWithBitmapsOnly;
            }
            set
            {
                _convertBackWhenPreviewAndPrintButWithBitmapsOnly = value;
                _isConvertBackWhenPreviewAndPrintButWithBitmapsOnlySet = true;
            }
        }
        private bool _isConvertBackWhenPreviewAndPrintButNoSubsettingAndWithBitmapsOnlySet;
        private bool _convertBackWhenPreviewAndPrintButNoSubsettingAndWithBitmapsOnly;

        public bool ConvertBackWhenPreviewAndPrintButNoSubsettingAndWithBitmapsOnly
        {
            get
            {
                return _convertBackWhenPreviewAndPrintButNoSubsettingAndWithBitmapsOnly;
            }
            set
            {
                _convertBackWhenPreviewAndPrintButNoSubsettingAndWithBitmapsOnly = value;
                _isConvertBackWhenPreviewAndPrintButNoSubsettingAndWithBitmapsOnlySet = true;
            }
        }
        private bool _isConvertBackWhenEditableSet;
        private bool _convertBackWhenEditable;

        public bool ConvertBackWhenEditable
        {
            get
            {
                return _convertBackWhenEditable;
            }
            set
            {
                _convertBackWhenEditable = value;
                _isConvertBackWhenEditableSet = true;
            }
        }
        private bool _isConvertBackWhenEditableButNoSubsettingSet;
        private bool _convertBackWhenEditableButNoSubsetting;

        public bool ConvertBackWhenEditableButNoSubsetting
        {
            get
            {
                return _convertBackWhenEditableButNoSubsetting;
            }
            set
            {
                _convertBackWhenEditableButNoSubsetting = value;
                _isConvertBackWhenEditableButNoSubsettingSet = true;
            }
        }
        private bool _isConvertBackWhenEditableButWithBitmapsOnlySet;
        private bool _convertBackWhenEditableButWithBitmapsOnly;

        public bool ConvertBackWhenEditableButWithBitmapsOnly
        {
            get
            {
                return _convertBackWhenEditableButWithBitmapsOnly;
            }
            set
            {
                _convertBackWhenEditableButWithBitmapsOnly = value;
                _isConvertBackWhenEditableButWithBitmapsOnlySet = true;
            }
        }
        private bool _isConvertBackWhenEditableButNoSubsettingAndWithBitmapsOnlySet;
        private bool _convertBackWhenEditableButNoSubsettingAndWithBitmapsOnly;

        public bool ConvertBackWhenEditableButNoSubsettingAndWithBitmapsOnly
        {
            get
            {
                return _convertBackWhenEditableButNoSubsettingAndWithBitmapsOnly;
            }
            set
            {
                _convertBackWhenEditableButNoSubsettingAndWithBitmapsOnly = value;
                _isConvertBackWhenEditableButNoSubsettingAndWithBitmapsOnlySet = true;
            }
        }
    }
}