//this code generated by T4

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Controls.Primitives;
using System.ComponentModel;
using System.Windows.Interop;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Documents.Serialization;
using System.Windows.Input;
using System.Windows.Media.Animation;
using System.Windows.Media;
using System.Windows.Media.TextFormatting;
using System.Windows.Annotations;
using System.Windows.Ink;
using System.Windows.Automation.Peers;
using System.Windows.Markup.Localizer;
using System.Windows.Media.Imaging;
using System.IO.Packaging;
using System.Security.RightsManagement;
using System.Windows.Threading;
using System.Windows.Media.Effects;
using System.Windows.Shell;
using System.Security.Permissions;
using System.Windows.Annotations.Storage;
using System.Diagnostics;

namespace Livet.Converters
{
    public class MediaPermissionVideoAndBooleanConverter : IValueConverter
    {
        //VM→View
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is bool)) throw new ArgumentException();

            if ((bool)value)
            {
                if (_isConvertWhenTrueSet)
                {
                    return ConvertWhenTrue;
                }
            }
            else
            {
                if (_isConvertWhenFalseSet)
                {
                    return ConvertWhenFalse;
                }
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertWhenTrueSet;
        private MediaPermissionVideo _convertWhenTrue;
        public MediaPermissionVideo ConvertWhenTrue
        {
            get
            {
                return _convertWhenTrue;
            }
            set
            {
                _convertWhenTrue = value;
                _isConvertWhenTrueSet = true;
            }
        }

        private bool _isConvertWhenFalseSet;
        private MediaPermissionVideo _convertWhenFalse;
        public MediaPermissionVideo ConvertWhenFalse
        {
            get
            {
                return _convertWhenFalse;
            }
            set
            {
                _convertWhenFalse = value;
                _isConvertWhenFalseSet = true;
            }
        }

        //View→VM
        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is MediaPermissionVideo)) throw new ArgumentException();

            var enumValue = (MediaPermissionVideo)value;

			switch(enumValue.ToString())
			{
				case "NoVideo":
					if (_isConvertBackWhenNoVideoSet)
					{
						return ConvertBackWhenNoVideo;
					}
					break;
				case "SiteOfOriginVideo":
					if (_isConvertBackWhenSiteOfOriginVideoSet)
					{
						return ConvertBackWhenSiteOfOriginVideo;
					}
					break;
				case "SafeVideo":
					if (_isConvertBackWhenSafeVideoSet)
					{
						return ConvertBackWhenSafeVideo;
					}
					break;
				case "AllVideo":
					if (_isConvertBackWhenAllVideoSet)
					{
						return ConvertBackWhenAllVideo;
					}
					break;
				default:
					throw new ArgumentException();
			}

            if (_isConvertBackDefaultBooleanValueSet)
            {
                return ConvertBackDefaultBooleanValue;
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertBackDefaultBooleanValueSet;
        private bool _convertBackDefaultBooleanValue;
        public bool ConvertBackDefaultBooleanValue
        {
            get
            {
                return _convertBackDefaultBooleanValue;
            }
            set
            {
                _convertBackDefaultBooleanValue = value;
				_isConvertBackDefaultBooleanValueSet = true;
            }
        }

        private bool _isConvertBackWhenNoVideoSet;
        private bool _convertBackWhenNoVideo;

        public bool ConvertBackWhenNoVideo
        {
            get
            {
                return _convertBackWhenNoVideo;
            }
            set
            {
                _convertBackWhenNoVideo = value;
                _isConvertBackWhenNoVideoSet = true;
            }
        }
        private bool _isConvertBackWhenSiteOfOriginVideoSet;
        private bool _convertBackWhenSiteOfOriginVideo;

        public bool ConvertBackWhenSiteOfOriginVideo
        {
            get
            {
                return _convertBackWhenSiteOfOriginVideo;
            }
            set
            {
                _convertBackWhenSiteOfOriginVideo = value;
                _isConvertBackWhenSiteOfOriginVideoSet = true;
            }
        }
        private bool _isConvertBackWhenSafeVideoSet;
        private bool _convertBackWhenSafeVideo;

        public bool ConvertBackWhenSafeVideo
        {
            get
            {
                return _convertBackWhenSafeVideo;
            }
            set
            {
                _convertBackWhenSafeVideo = value;
                _isConvertBackWhenSafeVideoSet = true;
            }
        }
        private bool _isConvertBackWhenAllVideoSet;
        private bool _convertBackWhenAllVideo;

        public bool ConvertBackWhenAllVideo
        {
            get
            {
                return _convertBackWhenAllVideo;
            }
            set
            {
                _convertBackWhenAllVideo = value;
                _isConvertBackWhenAllVideoSet = true;
            }
        }
    }
}