//this code generated by T4

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Controls.Primitives;
using System.ComponentModel;
using System.Windows.Interop;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Documents.Serialization;
using System.Windows.Input;
using System.Windows.Media.Animation;
using System.Windows.Media;
using System.Windows.Media.TextFormatting;
using System.Windows.Annotations;
using System.Windows.Ink;
using System.Windows.Automation.Peers;
using System.Windows.Markup.Localizer;
using System.Windows.Media.Imaging;
using System.IO.Packaging;
using System.Security.RightsManagement;
using System.Windows.Threading;
using System.Windows.Media.Effects;
using System.Windows.Shell;
using System.Security.Permissions;
using System.Windows.Annotations.Storage;
using System.Diagnostics;

namespace Livet.Converters
{
    public class ResizeModeAndBooleanConverter : IValueConverter
    {
        //VM→View
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is bool)) throw new ArgumentException();

            if ((bool)value)
            {
                if (_isConvertWhenTrueSet)
                {
                    return ConvertWhenTrue;
                }
            }
            else
            {
                if (_isConvertWhenFalseSet)
                {
                    return ConvertWhenFalse;
                }
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertWhenTrueSet;
        private ResizeMode _convertWhenTrue;
        public ResizeMode ConvertWhenTrue
        {
            get
            {
                return _convertWhenTrue;
            }
            set
            {
                _convertWhenTrue = value;
                _isConvertWhenTrueSet = true;
            }
        }

        private bool _isConvertWhenFalseSet;
        private ResizeMode _convertWhenFalse;
        public ResizeMode ConvertWhenFalse
        {
            get
            {
                return _convertWhenFalse;
            }
            set
            {
                _convertWhenFalse = value;
                _isConvertWhenFalseSet = true;
            }
        }

        //View→VM
        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is ResizeMode)) throw new ArgumentException();

            var enumValue = (ResizeMode)value;

			switch(enumValue.ToString())
			{
				case "NoResize":
					if (_isConvertBackWhenNoResizeSet)
					{
						return ConvertBackWhenNoResize;
					}
					break;
				case "CanMinimize":
					if (_isConvertBackWhenCanMinimizeSet)
					{
						return ConvertBackWhenCanMinimize;
					}
					break;
				case "CanResize":
					if (_isConvertBackWhenCanResizeSet)
					{
						return ConvertBackWhenCanResize;
					}
					break;
				case "CanResizeWithGrip":
					if (_isConvertBackWhenCanResizeWithGripSet)
					{
						return ConvertBackWhenCanResizeWithGrip;
					}
					break;
				default:
					throw new ArgumentException();
			}

            if (_isConvertBackDefaultBooleanValueSet)
            {
                return ConvertBackDefaultBooleanValue;
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertBackDefaultBooleanValueSet;
        private bool _convertBackDefaultBooleanValue;
        public bool ConvertBackDefaultBooleanValue
        {
            get
            {
                return _convertBackDefaultBooleanValue;
            }
            set
            {
                _convertBackDefaultBooleanValue = value;
				_isConvertBackDefaultBooleanValueSet = true;
            }
        }

        private bool _isConvertBackWhenNoResizeSet;
        private bool _convertBackWhenNoResize;

        public bool ConvertBackWhenNoResize
        {
            get
            {
                return _convertBackWhenNoResize;
            }
            set
            {
                _convertBackWhenNoResize = value;
                _isConvertBackWhenNoResizeSet = true;
            }
        }
        private bool _isConvertBackWhenCanMinimizeSet;
        private bool _convertBackWhenCanMinimize;

        public bool ConvertBackWhenCanMinimize
        {
            get
            {
                return _convertBackWhenCanMinimize;
            }
            set
            {
                _convertBackWhenCanMinimize = value;
                _isConvertBackWhenCanMinimizeSet = true;
            }
        }
        private bool _isConvertBackWhenCanResizeSet;
        private bool _convertBackWhenCanResize;

        public bool ConvertBackWhenCanResize
        {
            get
            {
                return _convertBackWhenCanResize;
            }
            set
            {
                _convertBackWhenCanResize = value;
                _isConvertBackWhenCanResizeSet = true;
            }
        }
        private bool _isConvertBackWhenCanResizeWithGripSet;
        private bool _convertBackWhenCanResizeWithGrip;

        public bool ConvertBackWhenCanResizeWithGrip
        {
            get
            {
                return _convertBackWhenCanResizeWithGrip;
            }
            set
            {
                _convertBackWhenCanResizeWithGrip = value;
                _isConvertBackWhenCanResizeWithGripSet = true;
            }
        }
    }
}