//this code generated by T4

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Controls.Primitives;
using System.ComponentModel;
using System.Windows.Interop;
using System.Windows.Data;
using System.Windows.Markup;
using System.Windows.Documents.Serialization;
using System.Windows.Input;
using System.Windows.Media.Animation;
using System.Windows.Media;
using System.Windows.Media.TextFormatting;
using System.Windows.Annotations;
using System.Windows.Ink;
using System.Windows.Automation.Peers;
using System.Windows.Markup.Localizer;
using System.Windows.Media.Imaging;
using System.IO.Packaging;
using System.Security.RightsManagement;
using System.Windows.Threading;
using System.Windows.Media.Effects;
using System.Windows.Shell;
using System.Security.Permissions;
using System.Windows.Annotations.Storage;
using System.Diagnostics;

namespace Livet.Converters
{
    public class TileModeAndBooleanConverter : IValueConverter
    {
        //VM→View
        public object Convert(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is bool)) throw new ArgumentException();

            if ((bool)value)
            {
                if (_isConvertWhenTrueSet)
                {
                    return ConvertWhenTrue;
                }
            }
            else
            {
                if (_isConvertWhenFalseSet)
                {
                    return ConvertWhenFalse;
                }
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertWhenTrueSet;
        private TileMode _convertWhenTrue;
        public TileMode ConvertWhenTrue
        {
            get
            {
                return _convertWhenTrue;
            }
            set
            {
                _convertWhenTrue = value;
                _isConvertWhenTrueSet = true;
            }
        }

        private bool _isConvertWhenFalseSet;
        private TileMode _convertWhenFalse;
        public TileMode ConvertWhenFalse
        {
            get
            {
                return _convertWhenFalse;
            }
            set
            {
                _convertWhenFalse = value;
                _isConvertWhenFalseSet = true;
            }
        }

        //View→VM
        public object ConvertBack(object value, Type targetType, object parameter, System.Globalization.CultureInfo culture)
        {
            if (!(value is TileMode)) throw new ArgumentException();

            var enumValue = (TileMode)value;

			switch(enumValue.ToString())
			{
				case "None":
					if (_isConvertBackWhenNoneSet)
					{
						return ConvertBackWhenNone;
					}
					break;
				case "FlipX":
					if (_isConvertBackWhenFlipXSet)
					{
						return ConvertBackWhenFlipX;
					}
					break;
				case "FlipY":
					if (_isConvertBackWhenFlipYSet)
					{
						return ConvertBackWhenFlipY;
					}
					break;
				case "FlipXY":
					if (_isConvertBackWhenFlipXYSet)
					{
						return ConvertBackWhenFlipXY;
					}
					break;
				case "Tile":
					if (_isConvertBackWhenTileSet)
					{
						return ConvertBackWhenTile;
					}
					break;
				default:
					throw new ArgumentException();
			}

            if (_isConvertBackDefaultBooleanValueSet)
            {
                return ConvertBackDefaultBooleanValue;
            }

            return DependencyProperty.UnsetValue;
        }

        private bool _isConvertBackDefaultBooleanValueSet;
        private bool _convertBackDefaultBooleanValue;
        public bool ConvertBackDefaultBooleanValue
        {
            get
            {
                return _convertBackDefaultBooleanValue;
            }
            set
            {
                _convertBackDefaultBooleanValue = value;
				_isConvertBackDefaultBooleanValueSet = true;
            }
        }

        private bool _isConvertBackWhenNoneSet;
        private bool _convertBackWhenNone;

        public bool ConvertBackWhenNone
        {
            get
            {
                return _convertBackWhenNone;
            }
            set
            {
                _convertBackWhenNone = value;
                _isConvertBackWhenNoneSet = true;
            }
        }
        private bool _isConvertBackWhenFlipXSet;
        private bool _convertBackWhenFlipX;

        public bool ConvertBackWhenFlipX
        {
            get
            {
                return _convertBackWhenFlipX;
            }
            set
            {
                _convertBackWhenFlipX = value;
                _isConvertBackWhenFlipXSet = true;
            }
        }
        private bool _isConvertBackWhenFlipYSet;
        private bool _convertBackWhenFlipY;

        public bool ConvertBackWhenFlipY
        {
            get
            {
                return _convertBackWhenFlipY;
            }
            set
            {
                _convertBackWhenFlipY = value;
                _isConvertBackWhenFlipYSet = true;
            }
        }
        private bool _isConvertBackWhenFlipXYSet;
        private bool _convertBackWhenFlipXY;

        public bool ConvertBackWhenFlipXY
        {
            get
            {
                return _convertBackWhenFlipXY;
            }
            set
            {
                _convertBackWhenFlipXY = value;
                _isConvertBackWhenFlipXYSet = true;
            }
        }
        private bool _isConvertBackWhenTileSet;
        private bool _convertBackWhenTile;

        public bool ConvertBackWhenTile
        {
            get
            {
                return _convertBackWhenTile;
            }
            set
            {
                _convertBackWhenTile = value;
                _isConvertBackWhenTileSet = true;
            }
        }
    }
}