
//this code generated by T4

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Interactivity;
using System.Windows.Controls.Primitives;
using System.Windows.Interop;
using System.ComponentModel;

namespace Livet.Behaviors.ControlBinding.OneWay
{
	public enum DataGridRowsPresenterUnbindableCanWriteProperty
	{
		CanHorizontallyScroll,
		CanVerticallyScroll
	}

	public class DataGridRowsPresenterSetStateToControlBehavior : Behavior<DataGridRowsPresenter>
	{
		public DataGridRowsPresenterSetStateToControlBehavior()
		{
		}

		public DataGridRowsPresenterUnbindableCanWriteProperty Property
        {
            get { return (DataGridRowsPresenterUnbindableCanWriteProperty)GetValue(PropertyProperty); }
            set { SetValue(PropertyProperty, value); }
        }

        public static readonly DependencyProperty PropertyProperty =
            DependencyProperty.Register(nameof(Property), typeof(DataGridRowsPresenterUnbindableCanWriteProperty), typeof(DataGridRowsPresenterSetStateToControlBehavior), new PropertyMetadata());

		[Bindable(BindableSupport.Default,BindingDirection.OneWay)]
		public object Source
        {
            get { return (object)GetValue(SourceProperty); }
            set { SetValue(SourceProperty, value); }
        }

        public static readonly DependencyProperty SourceProperty =
            DependencyProperty.Register(nameof(Source), typeof(object), typeof(DataGridRowsPresenterSetStateToControlBehavior), new PropertyMetadata(null,new PropertyChangedCallback(SourceChanged)));

        private static void SourceChanged(DependencyObject sender,DependencyPropertyChangedEventArgs e)
        {
			var thisObject = (DataGridRowsPresenterSetStateToControlBehavior)sender;
			
			if(thisObject.AssociatedObject == null)
			{
				return;
			}

            switch (thisObject.Property)
            {
                case DataGridRowsPresenterUnbindableCanWriteProperty.CanHorizontallyScroll:
					if(e.NewValue == null)
					{
						return;
					}
					if(e.OldValue != null)
					{
						if((System.Boolean)e.OldValue == (System.Boolean)e.NewValue)
						{
							return;
						}
					}
					thisObject.AssociatedObject.CanHorizontallyScroll = (System.Boolean)thisObject.Source;
                    break;
                case DataGridRowsPresenterUnbindableCanWriteProperty.CanVerticallyScroll:
					if(e.NewValue == null)
					{
						return;
					}
					if(e.OldValue != null)
					{
						if((System.Boolean)e.OldValue == (System.Boolean)e.NewValue)
						{
							return;
						}
					}
					thisObject.AssociatedObject.CanVerticallyScroll = (System.Boolean)thisObject.Source;
                    break;

            }
        }

		protected override void OnAttached()
        {
            base.OnAttached();

            SourceChanged(this, new DependencyPropertyChangedEventArgs(SourceProperty, null, Source));
        }
	}
}