
//this code generated by T4

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Reflection;
using System.Windows;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Interactivity;
using System.Windows.Controls.Primitives;
using System.Windows.Interop;
using System.ComponentModel;

namespace Livet.Behaviors.ControlBinding.OneWay
{
	public enum MediaElementUnbindableCanWriteProperty
	{
		Position,
		SpeedRatio
	}

	public class MediaElementSetStateToControlBehavior : Behavior<MediaElement>
	{
		public MediaElementSetStateToControlBehavior()
		{
		}

		public MediaElementUnbindableCanWriteProperty Property
        {
            get { return (MediaElementUnbindableCanWriteProperty)GetValue(PropertyProperty); }
            set { SetValue(PropertyProperty, value); }
        }

        public static readonly DependencyProperty PropertyProperty =
            DependencyProperty.Register(nameof(Property), typeof(MediaElementUnbindableCanWriteProperty), typeof(MediaElementSetStateToControlBehavior), new PropertyMetadata());

		[Bindable(BindableSupport.Default,BindingDirection.OneWay)]
		public object Source
        {
            get { return (object)GetValue(SourceProperty); }
            set { SetValue(SourceProperty, value); }
        }

        public static readonly DependencyProperty SourceProperty =
            DependencyProperty.Register(nameof(Source), typeof(object), typeof(MediaElementSetStateToControlBehavior), new PropertyMetadata(null,new PropertyChangedCallback(SourceChanged)));

        private static void SourceChanged(DependencyObject sender,DependencyPropertyChangedEventArgs e)
        {
			var thisObject = (MediaElementSetStateToControlBehavior)sender;
			
			if(thisObject.AssociatedObject == null)
			{
				return;
			}

            switch (thisObject.Property)
            {
                case MediaElementUnbindableCanWriteProperty.Position:
					if(e.NewValue == null)
					{
						return;
					}
					if(e.OldValue != null)
					{
						if((System.TimeSpan)e.OldValue == (System.TimeSpan)e.NewValue)
						{
							return;
						}
					}
					thisObject.AssociatedObject.Position = (System.TimeSpan)thisObject.Source;
                    break;
                case MediaElementUnbindableCanWriteProperty.SpeedRatio:
					if(e.NewValue == null)
					{
						return;
					}
					if(e.OldValue != null)
					{
						if((System.Double)e.OldValue == (System.Double)e.NewValue)
						{
							return;
						}
					}
					thisObject.AssociatedObject.SpeedRatio = (System.Double)thisObject.Source;
                    break;

            }
        }

		protected override void OnAttached()
        {
            base.OnAttached();

            SourceChanged(this, new DependencyPropertyChangedEventArgs(SourceProperty, null, Source));
        }
	}
}